### ISSUE TITLE
Lua error when going in game

### ISSUE THREAD

**Issue by suunr** [INPStarfall/Starfall#381]
```
[ERROR] addons/starfall/lua/starfall/editor.lua:50: attempt to index field 'globaltables' (a nil value)
  1. createCodeMap - addons/starfall/lua/starfall/editor.lua:50
   2. func - addons/starfall/lua/starfall/editor.lua:935
    3. unknown - lua/includes/extensions/net.lua:32
```

**Comment by awilliamson** [comment]
Are you up-to-date with develop branch? I've not experienced any errors with the editor on the latest code.

**Comment by davidsonbr** [comment]
[The code in question](https://github.com/INPStarfall/Starfall/blob/develop/lua/starfall/editor.lua#L50) was resolved by me in #369.

I agree w/ @awilliamson

**Comment by awilliamson** [comment]
Going to close this unless your problem still persists @suunrider ?
